USE playstoredb;
SELECT upper(DeveloperName) From Developers;
SELECT lower(DeveloperName) From Developers;
SELECT length(AppName) FROM Apps;
SELECT CategoryName,length(CategoryName) FROM Categories;
SELECT current_date(),current_time();
SELECT round(Rating,0) FROM Apps;
SELECT AppName,substring(AppName,1,5) FROM Apps;
SELECT concat(DeveloperName,Country) FROM Developers;
SELECT round(Rating,0) FROM Apps;
SELECT ceil(Price) FROM Apps;
SELECT FoundedYear FROM Developers;
SELECT CAST(Downloads AS char) FROM Apps;
SELECT upper(AppName),Rating FROM Apps;
SELECT substring(CategoryName,1,3) FROM Categories;
SELECT abs(Price-200) FROM Apps;
SELECT DeveloperName,length(DeveloperName) FROM Developers;
SELECT current_date(),current_timestamp();
SELECT convert(FoundedYear,char) FROM Developers;

